# Generated by Django 5.1.7 on 2025-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_auto_20250901_0239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in_time",
            field=models.TimeField(blank=True, help_text="Check - in time", null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_time",
            field=models.TimeField(blank=True, help_text="Check - out time", null=True),
        ),
        migrations.AlterField(
            model_name="bookingimporttemplate",
            name="checkin_field",
            field=models.CharField(default="check_in", help_text="CSV column name for check - in", max_length=100),
        ),
        migrations.AlterField(
            model_name="bookingimporttemplate",
            name="checkout_field",
            field=models.CharField(default="check_out", help_text="CSV column name for check - out", max_length=100),
        ),
        migrations.AlterField(
            model_name="bookingimporttemplate",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("csv", "CSV File"),
                    ("ical", "iCal / Calendar"),
                    ("airbnb", "Airbnb Export"),
                    ("vrbo", "VRBO Export"),
                    ("api", "API Integration"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn / Pool"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("stock_in", "Stock In"),
                    ("stock_out", "Stock Out"),
                    ("adjustment", "Adjustment"),
                    ("damage", "Damage / Loss"),
                    ("transfer", "Transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("staf", "Staff / Crew"), ("manager", "Manager"), ("superuser", "Superuser"), ("viewer", "Viewer")],
                default="staf",
                help_text="App role separate from Django is_staff / is_superuser.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("America / New_York", "Eastern Time (Tampa, FL)"),
                    ("America / Los_Angeles", "Pacific Time (San Jose, CA)"),
                    ("America / Chicago", "Central Time (Chicago, IL)"),
                    ("America / Denver", "Mountain Time (Denver, CO)"),
                    ("America / Phoenix", "Arizona Time (Phoenix, AZ)"),
                    ("America / Anchorage", "Alaska Time (Anchorage, AK)"),
                    ("Pacific / Honolulu", "Hawaii Time (Honolulu, HI)"),
                    ("Asia / Ho_Chi_Minh", "Vietnam Time (Ho Chi Minh City)"),
                    ("Europe / London", "GMT / BST (London, UK)"),
                    ("UTC", "UTC (Coordinated Universal Time)"),
                ],
                default="America / New_York",
                help_text="Your local timezone for displaying dates and times",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="can_delegate",
            field=models.BooleanField(
                default=False, help_text="Whether users with this role can grant / revoke this permission to others"
            ),
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="role",
            field=models.CharField(
                choices=[("staf", "Staff / Crew"), ("manager", "Manager"), ("superuser", "Superuser"), ("viewer", "Viewer")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="day_of_month",
            field=models.IntegerField(blank=True, help_text="For monthly schedules (1 - 31)", null=True),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="interval",
            field=models.IntegerField(default=1, help_text="Every X days / weeks / months"),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn / Pool"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("waiting_dependency", "Waiting for Dependency"),
                    ("in - progress", "In Progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn / Pool"),
                ],
                default="cleaning",
                max_length=20,
            ),
        ),
    ]
