# Generated by Django 5.1.7 on 2025-09-01 17:02

from django.db import migrations


def fix_timezone_spaces(apps, schema_editor):
    """
    Fix timezone values that contain spaces to use proper timezone identifiers
    """
    Profile = apps.get_model('api', 'Profile')
    
    # Map of incorrect timezone values to correct ones
    timezone_fixes = {
        'America / New_York': 'America/New_York',
        'America / Los_Angeles': 'America/Los_Angeles',
        'America / Chicago': 'America/Chicago',
        'America / Denver': 'America/Denver',
        'America / Phoenix': 'America/Phoenix',
        'America / Anchorage': 'America/Anchorage',
        'Pacific / Honolulu': 'Pacific/Honolulu',
        'Asia / Ho_Chi_Minh': 'Asia/Ho_Chi_Minh',
        'Europe / London': 'Europe/London',
    }
    
    for old_tz, new_tz in timezone_fixes.items():
        Profile.objects.filter(timezone=old_tz).update(timezone=new_tz)


def reverse_fix_timezone_spaces(apps, schema_editor):
    """
    Reverse the timezone fixes (for rollback)
    """
    Profile = apps.get_model('api', 'Profile')
    
    # Map of correct timezone values to incorrect ones
    timezone_fixes = {
        'America/New_York': 'America / New_York',
        'America/Los_Angeles': 'America / Los_Angeles',
        'America/Chicago': 'America / Chicago',
        'America/Denver': 'America / Denver',
        'America/Phoenix': 'America / Phoenix',
        'America/Anchorage': 'America / Anchorage',
        'Pacific/Honolulu': 'Pacific / Honolulu',
        'Asia/Ho_Chi_Minh': 'Asia / Ho_Chi_Minh',
        'Europe/London': 'Europe / London',
    }
    
    for old_tz, new_tz in timezone_fixes.items():
        Profile.objects.filter(timezone=old_tz).update(timezone=new_tz)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_alter_profile_timezone"),
    ]

    operations = [
        migrations.RunPython(fix_timezone_spaces, reverse_fix_timezone_spaces),
    ]
